name: AWS-LC

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/aws-lc-template.yml
    with:
      command: "from matrix import determine_latest_aws_lc; print(determine_latest_aws_lc(''))"
